{
 "title": "System: Overview",
 "tags": [ "System" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_load1, cluster)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1{cluster=\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time_seconds{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} - node_boot_time_seconds{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"})) / node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} * 100"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Load 1m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} or (node_memory_MemFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"})) or sum(irate(node_cpu_seconds_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Buffers_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} + node_memory_Cached_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_forks_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_context_switches_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_intr_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) or irate(node_intr_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_receive_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Inbound: {{ device }}"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[5m])",
     "legendFormat": "Outbound: {{ device }}"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes_total{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"} - node_memory_SwapFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree_bytes{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_maximum{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_allocated{cluster=\"$cluster\", instance=~\"$host(:[0-9]+)?\"}",
     "legendFormat": "Allocated"
    }
   ]
  }
 ]
}